spring:
  profiles:
    active: "default,QA"
  application:
    name: java-mentoring-adv
  h2:
    console:
      enabled: true
      path: /h2
#  jpa:
#    show-sql: true

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
